Repository yildiraykoyuncu/js-drum-kit, pull requests merged in 2020-07, with the labels that each got.

#15 Creating folder and upload files
  sounds/boom.wav
  sounds/clap.wav
  sounds/hihat.wav
  sounds/kick.wav
  sounds/openhat.wav
  sounds/ride.wav
  sounds/snare.wav
  sounds/tink.wav
  sounds/tom.wav
Labels: Play Sound

#17 Creating keydown listener
  index.html
Labels: Play Sound

#18 Creating playSound Handler
  index.html
Labels: Play Sound

#16 Creating audio-tag and linking with key
  index.html
Labels: Play Sound

#26 See beauty
  image/photo-1506755594592-349d12a7c52a.jpeg
  index.html
  style.css
Labels: See Beauty

#23 added keys
  index.html
Labels: Dom

#21 added container div for the keys
  index.html
Labels: Dom

#33 Display keyboard
  index.html
Labels: Dom

#32 finished readme
  README.md
  image/screen-shot.png
Labels: documentation

#31 Finished development strategy
  development-strategy.md
Labels: documentation

#27 Playsounds
  index.html
  sounds/boom.wav
  sounds/clap.wav
  sounds/hihat.wav
  sounds/kick.wav
  sounds/openhat.wav
  sounds/ride.wav
  sounds/snare.wav
  sounds/tink.wav
  sounds/tom.wav
Labels: Play Sound, enhancement
